### ISSUE TITLE
Collections mistakenly cause dirty buffer state

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-collection#11]
Opening the editor of a collection causes the paths used in its template to show as modified in Simpla's `'buffer'` state (ie: `Simpla.getState('buffer')`) even when no changes have occurred. Assuming this has to do with the fact that Simpla is now returning deep clones of data, rather than pointers, which makes it appear different to the API for complex data like Arrays?

This breaks simpla-admin's unsaved changes check, meaning that every time you exit a page after interacting with a collection (even if you just saved), you get told there are unsaved changes on your page.

**Comment by bedeoverend** [comment]
@seaneking I'm marking this as closed, as https://github.com/simplaio/simpla/commit/25cfdcc0df5c778d3bcd535d62528576c781dfe1 fixed it for me. But I also wasn't able to replicate the way you described, though I certainly was getting some false positives in other checks. Let me know if you're still getting it, but will need other steps to replicate.

**Comment by madeleineostoja** [comment]
:+1:
