### ISSUE TITLE
Collection should prefetch items

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-collection#4]
Once [prefetch support](https://github.com/simplaio/simpla/issues/65) has landed in Simpla, a collection should start prefetching all the data its children need rather than waiting for DOM to be stamped and children to request data themselves. 

```js
pathChanged(path) {
  Simpla.prefetch(path)
}
```

This can work hand-in-hand #3, by prefetching the data for the next batch of items to be rendered so that infinite scrolling/lazy-loading is instantaeneous

**Comment by bedeoverend** [comment]
Closing this as `prefetch` has been ditched in v3. Happy to reopen when / if a similar alternative is brought into Simpla
